name: Build with GitHub Action for GraalVM
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # 메이저만 사용시 21
          distribution: 'graalvm'     # 커뮤니티 사용시 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
