name: Build with GitHub Action for GraalVM
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'      # 메이저만 사용시 21
          distribution: 'graalvm'     # 커뮤니티 사용시 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run HelloWorld.java
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac HelloWorld.java
          native-image HelloWorld
          ./helloworld

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-ubuntu-latest
          path: helloworld*