name: After PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Run a script after PR merge
        run: echo "PR was merged!"