name: 'main PR시엔 nativeTest를 합니다.'
on:
  pull_request:
#    branches: [ main ]
    branches-ignore: [ 'main' ]

jobs:
  PR_NativeTest:
    name: Native Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: 'GitHub Action for GraalVM'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'gradle'
      #
      #      - name: Setup Gradle 8.7+
      #        id: setup-gradle
      #        uses: gradle/actions/setup-gradle@v3
      #        with:
      #          gradle-version: 8.7

      - name: Gradle nativeTest
        run: |
          gradle nativeTest jacocoTestCoverageVerification --stacktrace --no-daemon --parallel --scan

      - name: Generate JaCoCo Badge
        id: jacoco
        if: matrix.os == 'ubuntu-latest'
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-coverage-badge: false
          coverage-badge-filename: jacoco.svg
          generate-branches-badge: false
          branches-badge-filename: branches.svg
          generate-coverage-endpoint: false
          coverage-endpoint-filename: jacoco.json
          generate-branches-endpoint: false
          branches-endpoint-filename: branches.json
          generate-summary: false
          summary-filename: coverage-summary.json
          coverage-label: '전체 커버리지'
          branches-label: '브렌치 커버리지'
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          intervals: 100 90 80 70 60 0
          on-missing-report: fail
          fail-if-coverage-less-than: 70
          fail-if-branches-less-than: 80
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false
          generate-workflow-summary: true
          workflow-summary-heading: '테스트 커버리지 요약'

      - name: Log coverage percentage
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: '${{ matrix.os }}-${{ job.status }}'
          author_name: GeunChang Ahn
          job_name: PR_NativeTest
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          #          mention: here
          if_mention: success, failure, cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}