name: Gradle test On GitHub Action
on:
  push:
    branches-ignore:
      - 'main'

permissions:
  contents: write

jobs:
  onPushTest:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - uses: actions/setup-java@v4
        id: setup-java-21
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'
#          cache-dependency-path: | # optional
#            sub-project/*.gradle*
#            sub-project/**/gradle-wrapper.properties

      - name: Setup Gradle 8.7+
        id: setup-gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: test
        run: gradle clean test jacocoTestCoverageVerification --stacktrace --no-daemon --parallel
      #          ./gradlew clean test jacocoTestCoverageVerification --stacktrace --no-daemon

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg
          generate-coverage-endpoint: false
          coverage-endpoint-filename: jacoco.json
          generate-branches-endpoint: false
          branches-endpoint-filename: branches.json
          generate-summary: false
          summary-filename: coverage-summary.json
          coverage-label: '테스트 Coverage'
          branches-label: 'branch 커버리지'
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          intervals: 100 90 80 70 60 0
          on-missing-report: fail
          fail-if-coverage-less-than: 70
          fail-if-branches-less-than: 80
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false
          generate-workflow-summary: true
          workflow-summary-heading: JaCoCo Test Coverage Summary

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"


#       현재 branch 전제 경로: ${{ github.ref }} -> 모양은 `refs/heads/branch-name`
#       branch name: ${{ github.ref_name }}

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[Action] commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: GeunChang Ahn
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        #          mention: here
        #          if_mention: failure, cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}