name: Gradle test On GitHub Action
on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  onPushTest:
    if: github.event.pull_request.opened == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: setup-java-21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      - name: test
        run: |
          echo "Available processors: $(nproc)"
          gradle test jacocoTestCoverageVerification --no-daemon --parallel

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          author_name: GeunChang Ahn
          job_name: onPushTest
          fields: repo,message,commit,author,eventName,ref,workflow,job,took,
          mention: '@rkaehdaos'
          if_mention: 'success,failure,cancelled'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}