name: Build with GitHub Action for GraalVM
on: push

jobs:
  gradlew_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - uses: actions/setup-java@v4
        id: setup-java-21
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
#          cache: 'gradle' # 밑의 액션의 default가 caching
#          cache-dependency-path: | # optional
#            sub-project/*.gradle*
#            sub-project/**/gradle-wrapper.properties

      - name: Setup Gradle 8.7+
        id: setup-gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: test
        run: gradle clean test --stacktrace --no-daemon
#          ./gradlew clean test jacocoTestCoverageVerification --stacktrace --no-daemon

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: GeunChang Ahn
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        #          mention: here
        #          if_mention: failure, cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}