name: Gradle Push Build On GitHub Action
on:
  push:
    branches-ignore: [ 'main' ]
    tags-ignore: [ 'beta*' ]
    paths-ignore: [ '.github/**' ]

jobs:
  onPushBuild:
    name: Push_build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: '소스 checkout'
        uses: actions/checkout@v4

      - name: 'jdk21 setup'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: 'gradle test'
        run: |
          echo "Available processors: $(nproc)"
          ./gradlew build --no-daemon --stacktrace --parallel

      - name: 'slack 알림'
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          author_name: my workflow bot
          fields: repo,message,commit,author,eventName,ref,workflow,job,took,
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}